### Create User

POST http://localhost:3000/auth/signup
Content-Type:  application/json

{
    "email": "test@test.com",
    "password": "pass123"
}

### User signin

POST http://localhost:3000/auth/signin
Content-Type:  application/json

{
    "email": "test@test.com",
    "password": "pass123"
}

### Find particular User with a given ID

GET http://localhost:3000/auth/1

### Find particular User with a given email
GET http://localhost:3000/auth?email

### Delete particular User with a given ID
DELETE http://localhost:3000/auth/3

### Update particular User with a given ID

PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "password": "pas123"
}

### Set color
GET http://localhost:3000/auth/colors/blue

### Get Colors
GET http://localhost:3000/auth/colors